# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ninely的小站
subtitle: 
description: 专注于WEB端开发
author: Ninely
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.ninely.top
root: /
permalink: post/:category/:year-:month-:day-:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
    - 'README.md'
    - 'demo/**'
    - 'demo/*'
    - 'demo/**/*'
    - 'demo/**/**'
    - 'baidu_verify_aHNKZW1Pns.html'
    - 'googlebcc164df46d7dd3d.html'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: other
category_map:
    programming: programming
    life: life
    other: other
    github: github
    hexo: hexo
    blog: blog
    html: html
    javascript: javascript
tag_map:
    html: html
    hexo: hexo
    other: other
    github: github
    git: git
    js: js
    css: css
    next: next

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  # type: git
  # elfwalk改为你的github用户名
  # repository: https://github.com/ninely/ninely.github.io.git
  # branch: master
  type: git
  repo:
	  github: git@github.com:ninely/ninely.github.io.git,master
	  coding: git@git.coding.net:ninely/ninely.git,master

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

# hexo 头像
avatar: /images/avatar.jpeg

# hexo sitemap网站地图
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# 多说评论
duoshuo_shortname: ninely

# 百度统计
# baidu_analytics: 3ceeecb0c5ec3e5ea30ee0c669f7af32
baidu_analytics: bf4716e4a962d9cd03066126c9e16267

# 网站标志
favicon: /images/favicon.ico

# Google Analytics
# google_analytics: UA-87468310-1

# 百度/谷歌/本地 自定义站点内容搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
